apiVersion: v1
kind: Service
metadata:
  name: {{ include "workload-resource-controller.fullname" . }}
spec:
  selector:
    app: {{ include "workload-resource-controller.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
