apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workload-resource-controller.serviceAccountName" . }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId }}
    azure.workload.identity/tenant-id: 0fadfa8b-6e6e-44b1-a381-6203bfe1a199
    azureIdentityName: {{ .Values.workloadIdentity.azureIdentityName }}
